import cv2
import numpy as np
import os
import random
import string

def generate_random_filename():
    """Generate a random filename with .py extension"""
    random_name = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    return f"{random_name}.py"

def main():
    # Create a sample image for demonstration
    sample_image = np.zeros((300, 300, 3), dtype=np.uint8)
    sample_image[:] = [255, 100, 0]  # Blue color background
    
    # Draw some shapes to make the image more interesting
    cv2.rectangle(sample_image, (50, 50), (250, 250), (0, 255, 0), 2)
    cv2.putText(sample_image, 'Sample Image', (70, 150), 
                cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    
    print("Created sample image")
    
    # Generate random filename
    random_filename = generate_random_filename()
    
    # Save image data to the randomly named .py file
    # Actually, let's save the script content to the random .py file as per the requirement
    script_content = '''import cv2
import numpy as np

# This is a randomly named Python file generated by the image processor script

# Sample image creation and processing code
image = np.zeros((200, 200, 3), dtype=np.uint8)
image[:] = [100, 150, 200]  # Light blue background
cv2.rectangle(image, (25, 25), (175, 175), (0, 255, 0), 2)

# In a real scenario, you would load an image file like this:
# image = cv2.imread('path_to_your_image.jpg')
# cv2.imshow('Loaded Image', image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

print("This is a randomly named Python file containing image processing code")
'''
    
    with open(random_filename, 'w') as f:
        f.write(script_content)
    
    print(f"Script saved to randomly named file: {random_filename}")

if __name__ == "__main__":
    main()