---
- name: Restart a service
  hosts: localhost
  become: yes
  tasks:
    - name: Restart service
      systemd:
        name: "{{ service_name | default('nginx') }}"
        state: restarted
      notify: 
        - verify service is running

  handlers:
    - name: verify service is running
      systemd:
        name: "{{ service_name | default('nginx') }}"
        state: started