#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;

# Function to generate a random filename
sub generate_random_filename {
    my $length = 8;
    my @chars = ('a'..'z', 'A'..'Z', '0'..'9');
    my $random_string = '';
    $random_string .= $chars[rand @chars] for 1..$length;
    return $random_string . ".pl";
}

# Function to parse log file and count errors
sub parse_log_file {
    my ($log_file) = @_;
    
    # Check if log file exists
    unless (-e $log_file) {
        print "Error: Log file '$log_file' does not exist.\n";
        return;
    }
    
    # Hash to store error counts
    my %error_counts = ();
    my $total_errors = 0;
    
    # Open and read the log file
    open(my $fh, '<', $log_file) or die "Cannot open file '$log_file': $!";
    
    while (my $line = <$fh>) {
        chomp $line;
        
        # Look for lines containing ERROR
        if ($line =~ /ERROR/) {
            # Extract the error message part (after timestamp and ERROR keyword)
            if ($line =~ /\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} ERROR (.+)/) {
                my $error_msg = $1;
                $error_counts{$error_msg}++;
                $total_errors++;
            } else {
                # If the format is different, count the whole line as error
                $error_counts{$line}++;
                $total_errors++;
            }
        }
    }
    
    close($fh);
    
    return (\%error_counts, $total_errors);
}

# Function to save results to a random named Perl file
sub save_results {
    my ($error_counts_ref, $total_errors) = @_;
    
    my $random_filename = generate_random_filename();
    my $output_file = "/workspace/$random_filename";
    
    open(my $fh, '>', $output_file) or die "Cannot open file '$output_file': $!";
    
    print $fh "#!/usr/bin/perl\n";
    print $fh "# Generated by log parser script\n";
    print $fh "# Log error statistics\n\n";
    
    print $fh "# Total errors found: $total_errors\n";
    print $fh "my \$total_errors = $total_errors;\n\n";
    
    print $fh "# Error counts by message:\n";
    print $fh "my \%error_counts = (\n";
    
    foreach my $error_msg (sort keys %$error_counts_ref) {
        my $count = $error_counts_ref->{$error_msg};
        # Escape special characters for Perl string
        my $escaped_msg = $error_msg;
        $escaped_msg =~ s/\\/\\\\/g;  # Escape backslashes
        $escaped_msg =~ s/'/\\'/g;    # Escape single quotes
        print $fh "    '$escaped_msg' => $count,\n";
    }
    
    print $fh ");\n\n";
    print $fh "# Print the results\n";
    print $fh "print \"Total errors: \$total_errors\\n\";\n";
    print $fh "print \"Error details:\\n\";\n";
    print $fh "foreach my \$msg (sort keys \%error_counts) {\n";
    print $fh "    print \"  \$error_counts{\$msg} x \$msg\\n\";\n";
    print $fh "}\n";
    
    close($fh);
    
    print "Results saved to: $output_file\n";
    return $output_file;
}

# Main execution
sub main {
    my $log_file = $ARGV[0] || '/workspace/test.log';
    
    print "Parsing log file: $log_file\n";
    
    my ($error_counts_ref, $total_errors) = parse_log_file($log_file);
    
    if (defined $error_counts_ref) {
        print "Total errors found: $total_errors\n";
        print "Error details:\n";
        
        foreach my $error_msg (sort keys %$error_counts_ref) {
            print "  $error_counts_ref->{$error_msg} x $error_msg\n";
        }
        
        print "\n";
        
        my $output_file = save_results($error_counts_ref, $total_errors);
        print "Results saved to: $output_file\n";
    }
}

# Run the main function
main();