#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;

# Function to generate a random filename
sub generate_random_filename {
    my $length = 8;
    my @chars = ('a'..'z', 'A'..'Z', '0'..'9');
    my $random_name = '';
    for (1..$length) {
        $random_name .= $chars[rand @chars];
    }
    return $random_name . '.pl';
}

# Check if log file is provided as argument
if (@ARGV != 1) {
    print "Usage: $0 <log_file_path>\n";
    print "Example: $0 /path/to/your/logfile.log\n";
    exit 1;
}

my $log_file = $ARGV[0];

# Check if the log file exists
unless (-e $log_file) {
    print "Error: Log file '$log_file' does not exist!\n";
    exit 1;
}

# Open and read the log file
open(my $fh, '<', $log_file) or die "Could not open file '$log_file': $!";

my %error_counts = ();
my $total_lines = 0;

while (my $line = <$fh>) {
    chomp $line;
    $total_lines++;
    
    # Look for common error patterns in the log line
    if ($line =~ /(?:ERROR|FATAL|CRITICAL|Exception|Error)/i) {
        # Extract the specific error type
        if ($line =~ /(?:ERROR|FATAL|CRITICAL|Exception):\s*([^\n\r]+)/i) {
            my $error_type = $1;
            # Extract just the first part of the error as the key
            $error_type =~ s/\s+.*$//;
            $error_counts{$error_type}++;
        } elsif ($line =~ /(Error\s+\w+)/i) {
            # Alternative pattern for errors like "Error 404"
            $error_counts{uc($1)}++;
        } else {
            # Generic error count if no specific type found
            $error_counts{"OTHER_ERROR"}++;
        }
    }
}

close($fh);

# Generate random filename for output
my $output_file = generate_random_filename();

# Write the results to the randomly named Perl file
open(my $out_fh, '>', $output_file) or die "Could not create output file '$output_file': $!";

print $out_fh "#!/usr/bin/perl\n";
print $out_fh "# Generated by log_parser.pl\n";
print $out_fh "# Log file processed: $log_file\n";
print $out_fh "# Total lines processed: $total_lines\n\n";

print $out_fh "# Error statistics:\n";
my $total_errors = 0;
foreach my $error_type (sort keys %error_counts) {
    print $out_fh "# $error_type: $error_counts{$error_type}\n";
    $total_errors += $error_counts{$error_type};
}

print $out_fh "\n# Total errors found: $total_errors\n";

# Create a Perl data structure with the error counts
print $out_fh "\nmy \%error_statistics = (\n";
foreach my $error_type (sort keys %error_counts) {
    print $out_fh "    '$error_type' => $error_counts{$error_type},\n";
}
print $out_fh ");\n\n";

print $out_fh "# Print summary\n";
print $out_fh "print \"Log Analysis Summary for: $log_file\\n\";\n";
print $out_fh "print \"Total lines processed: $total_lines\\n\";\n";
print $out_fh "print \"Total errors found: $total_errors\\n\";\n";
print $out_fh "print \"\\nDetailed error counts:\\n\";\n";
print $out_fh "foreach my \$error (sort keys \%error_statistics) {\n";
print $out_fh "    print \"\$error: \$error_statistics{\$error}\\n\";\n";
print $out_fh "}\n";

close($out_fh);

print "Log analysis completed!\n";
print "Results saved to: $output_file\n";
print "Total errors found: $total_errors\n";
print "Total lines processed: $total_lines\n";