"""
Order Processing Service Client
This is a simple client to test the Thrift service for processing orders.
"""

import sys
from datetime import datetime
from thrift import Thrift
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol

# Add the generated code to the path
sys.path.append('/workspace/gen-py')

from order_service import OrderProcessingService
from order_service.ttypes import *

def main():
    try:
        # Make socket
        transport = TSocket.TSocket('localhost', 9090)

        # Buffering is critical. Raw sockets are very slow
        transport = TTransport.TBufferedTransport(transport)

        # Wrap in a protocol
        protocol = TBinaryProtocol.TBinaryProtocol(transport)

        # Create a client to use the protocol encoder
        client = OrderProcessingService.Client(protocol)

        # Connect!
        transport.open()

        # Create a test order
        item1 = OrderItem(
            productId="PROD-001",
            productName="Laptop",
            quantity=1,
            price=1200.00
        )
        
        item2 = OrderItem(
            productId="PROD-002",
            productName="Mouse",
            quantity=2,
            price=25.00
        )

        order = Order(
            orderId="",  # Will be generated by the server
            customerId="CUST-001",
            items=[item1, item2],
            totalAmount=0.0,  # Will be calculated by the server
            status=OrderStatus.UNKNOWN_TO_SDK_VERSION,  # Will be set to PENDING by the server
            shippingAddress="123 Main St, Anytown, USA",
            createdAt=""
        )

        # Create the order
        print("Creating order...")
        response = client.createOrder(order)
        print(f"Response: {response.message}")
        
        if response.success:
            created_order = response.order
            print(f"Order ID: {created_order.orderId}")
            print(f"Order Status: {OrderStatus._VALUES_TO_NAMES[created_order.status]}")
            print(f"Total Amount: ${created_order.totalAmount}")
            
            # Get the order back
            print("\nGetting order...")
            get_response = client.getOrder(created_order.orderId)
            if get_response.success:
                print(f"Retrieved order: {get_response.order.orderId}")
                
                # Update order status
                print("\nUpdating order status to CONFIRMED...")
                update_response = client.updateOrderStatus(created_order.orderId, OrderStatus.CONFIRMED)
                print(f"Update response: {update_response.message}")
                
                # Get customer orders
                print("\nGetting orders for customer...")
                customer_orders = client.getOrdersByCustomer("CUST-001")
                print(f"Found {len(customer_orders)} orders for customer CUST-001")
                
                # Cancel the order
                print("\nCancelling order...")
                cancel_response = client.cancelOrder(created_order.orderId)
                print(f"Cancel response: {cancel_response.message}")

        # Close!
        transport.close()

    except Thrift.TException as tx:
        print(f"Thrift exception: {tx.message}")

if __name__ == '__main__':
    main()