# Класс Puppet для настройки сети
class PuppetNetworkConfig
  # Конструктор класса
  # @param interface [String] имя сетевого интерфейса (например, 'eth0')
  # @param ip [String] IP-адрес (например, '192.168.1.10')
  # @param netmask [String] маска подсети (например, '255.255.255.0')
  # @param gateway [String] шлюз по умолчанию (например, '192.168.1.1')
  # @param dns_servers [Array<String>] массив DNS-серверов (например, ['8.8.8.8', '1.1.1.1'])
  def initialize(interface, ip, netmask, gateway, dns_servers = ['8.8.8.8'])
    @interface = interface
    @ip = ip
    @netmask = netmask
    @gateway = gateway
    @dns_servers = dns_servers
  end

  # Генерирует строку конфигурации для интерфейса в формате Linux (Debian/Ubuntu)
  # @return [String] строка конфигурации
  def generate_interface_config
    config = <<~CONFIG
      auto #{@interface}
      iface #{@interface} inet static
          address #{@ip}
          netmask #{@netmask}
          gateway #{@gateway}
          dns-nameservers #{@dns_servers.join(' ')}
    CONFIG
    config
  end

  # Генерирует строку конфигурации для DNS-серверов в /etc/resolv.conf
  # @return [String] строка конфигурации DNS
  def generate_dns_config
    dns_config = "# Generated by PuppetNetworkConfig\n"
    @dns_servers.each do |server|
      dns_config += "nameserver #{server}\n"
    end
    dns_config
  end

  # Выводит сгенерированные конфигурации в STDOUT
  def print_configs
    puts "Конфигурация интерфейса для #{@interface}:"
    puts generate_interface_config
    puts "\nКонфигурация DNS:"
    puts generate_dns_config
  end
end

# Пример использования
# config = PuppetNetworkConfig.new('eth0', '192.168.1.100', '255.255.255.0', '192.168.1.1', ['8.8.8.8', '1.1.1.1'])
# config.print_configs