---
- name: Restart a service
  hosts: localhost
  become: yes
  vars:
    service_name: apache2
  tasks:
    - name: Restart the specified service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted
      notify: Service restarted successfully

  handlers:
    - name: Service restarted successfully
      ansible.builtin.debug:
        msg: "The service {{ service_name }} has been restarted successfully"