apiVersion: v1
kind: Service
metadata:
  name: my-random-service
  labels:
    app: my-random-app
spec:
  selector:
    app: my-random-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP