service: my-nodejs-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # You can change this to your preferred region

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get