#!/usr/bin/perl
# Generated by log parser script
# Log error statistics

# Total errors found: 5
my $total_errors = 5;

# Error counts by message:
my %error_counts = (
    'Database connection failed' => 3,
    'File not found' => 1,
    'Invalid user credentials' => 1,
);

# Print the results
print "Total errors: $total_errors\n";
print "Error details:\n";
foreach my $msg (sort keys %error_counts) {
    print "  $error_counts{$msg} x $msg\n";
}
