#!/usr/bin/perl
# Generated by log_parser.pl
# Log file processed: /workspace/test.log
# Total lines processed: 14

# Error statistics:
# ERROR DATABASE: 2
# ERROR ERROR: 2
# ERROR EXCEPTION: 1
# ERROR FAILED: 1
# OTHER_ERROR: 1

# Total errors found: 7

my %error_statistics = (
    'ERROR DATABASE' => 2,
    'ERROR ERROR' => 2,
    'ERROR EXCEPTION' => 1,
    'ERROR FAILED' => 1,
    'OTHER_ERROR' => 1,
);

# Print summary
print "Log Analysis Summary for: /workspace/test.log\n";
print "Total lines processed: 14\n";
print "Total errors found: 7\n";
print "\nDetailed error counts:\n";
foreach my $error (sort keys %error_statistics) {
    print "$error: $error_statistics{$error}\n";
}
