# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import profile_service_pb2 as profile__service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in profile_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub(object):
    """Service definition for profile management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/profile_service.ProfileService/GetProfile',
                request_serializer=profile__service__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=profile__service__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.SaveProfile = channel.unary_unary(
                '/profile_service.ProfileService/SaveProfile',
                request_serializer=profile__service__pb2.SaveProfileRequest.SerializeToString,
                response_deserializer=profile__service__pb2.SaveProfileResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """Service definition for profile management
    """

    def GetProfile(self, request, context):
        """Get a user profile by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProfile(self, request, context):
        """Save a user profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=profile__service__pb2.GetProfileRequest.FromString,
                    response_serializer=profile__service__pb2.GetProfileResponse.SerializeToString,
            ),
            'SaveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProfile,
                    request_deserializer=profile__service__pb2.SaveProfileRequest.FromString,
                    response_serializer=profile__service__pb2.SaveProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile_service.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profile_service.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Service definition for profile management
    """

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile_service.ProfileService/GetProfile',
            profile__service__pb2.GetProfileRequest.SerializeToString,
            profile__service__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile_service.ProfileService/SaveProfile',
            profile__service__pb2.SaveProfileRequest.SerializeToString,
            profile__service__pb2.SaveProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
